### ISSUE TITLE
maven install failure

### ISSUE THREAD

**Issue by concrain** [ballerina-lang/tools-distribution#59]
The snapshot is not showing for the 'workspace-service-0.8.15-SNAPSHOT-jar' directory.
Instead the directory is named 'workspace-service-0.8.15-20170311.192549-6-jar'
causing an install failure.

org.apache.maven.plugin.assembly.archive.ArchiveCreationException: Error creating assembly archive Ballerina Tools: Failed to read filesystem attributes for: /Applications/ballerina/target/extracted-distributions/workspace-service-0.8.15-SNAPSHOT-jar/netty-transports.yml

Caused by: java.nio.file.NoSuchFileException: /Applications/ballerina/target/extracted-distributions/workspace-service-0.8.15-SNAPSHOT-jar/netty-transports.yml

**Comment by sameera-jayasoma** [comment]
Hi 

Are you still getting this error?

Thanks,
Sameera.

**Comment by concrain** [comment]
Hello, I just did a fresh pull and everything compiled.  I guess it might have been a minor release bug.

Im looking forward to playing with this language,
Russel

**Comment by uthaiyashankar** [comment]
Resolving as per last comment.
