### ISSUE TITLE
composer script available in two locations

### ISSUE THREAD

**Issue by dilinisg** [ballerina-lang/tools-distribution#91]
**Steps**
1. Build the tools distribution
2. Navigate to /tools-distribution/modules/ballerina-tools/bin

**Improvement**
The following files are available in this location which is confusing and do not work. Users can mistakenly run these scripts. Can we remove if these are not necessary?
composer  composer.bat  version.txt

**Note**: The correct location is /tools-distribution/modules/ballerina-tools/target/ballerina-tools-0.87-SNAPSHOT/bin

**Comment by uthaiyashankar** [comment]
These are needed, and are the files copied to the target zip.
